# -*- coding: utf-8 -*-
"""video_compressor_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZHHEQ2Hqy9UIKTky_DpnVngRK2kVf1n

# 🎬 Video Compressor v4 — FAST Edition

### Why fast?
- ✅ **Google Drive mount** — no upload/download wait. Read & write directly.
- ✅ **`ultrafast` preset** — 10x faster encode. Perfect for 2–4s clips.
- ✅ **Multi-thread** — all CPU cores used in parallel.

### Setup (one time only):
1. Put your ZIP (e.g. `SB01 - পতাকা [Potaka].zip`) anywhere in Google Drive
2. Set `ZIP_PATH` in Cell 2 to that path
3. Run all cells → output ZIP appears in same Drive folder instantly

---
"""

# ============================================================
# CELL 1: Install + Mount Google Drive
# ============================================================
!apt-get update -qq
!apt-get install -y ffmpeg -qq
!pip install tqdm -q

from google.colab import drive
drive.mount('/content/drive')

import subprocess
r = subprocess.run(['ffmpeg', '-version'], capture_output=True, text=True)
print('✅ FFmpeg:', r.stdout.split('\n')[0])
print('✅ Google Drive mounted at /content/drive/MyDrive/FYDP Master Folder/FYDP video/')

import os, glob
import shutil # Import shutil for rmtree

# 👇 CHANGE THIS — path to your folder of videos inside Google Drive
INPUT_SOURCE_PATH = '/content/drive/MyDrive/FYDP Master Folder/FYDP video/SB05 - কাগজ [Kagoz]' # Assumed folder path, as per user

# ── Compression settings ─────────────────────────────────────
CRF        = 28       # Quality: 24 (best) → 32 (smallest). 28 = excellent
CODEC      = 'libx265'  # libx265 = smallest | libx264 = most compatible
PRESET     = 'ultrafast' # ultrafast = 10x faster. Quality still great for short clips
MAX_WIDTH  = None     # None = original size. 720 or 480 = smaller
KEEP_AUDIO = True     # False = remove audio (saves 5–15 KB each)
OUTPUT_EXT = 'mp4'
# ─────────────────────────────────────────────────────────────

# Initialize variables that are used in subsequent cells
INPUT_DIR       = '/content/work/input'
OUTPUT_DIR      = '/content/work/output'
extracted       = [] # List to hold paths of videos to be processed
SERIAL_PREFIX   = 'unknown_source'
OUTPUT_ZIP_PATH = '' # Will be defined based on INPUT_SOURCE_PATH
zip_filename    = '' # Used in CELL 4

# Clear INPUT_DIR before populating it to avoid processing old files
if os.path.exists(INPUT_DIR):
    shutil.rmtree(INPUT_DIR)
os.makedirs(INPUT_DIR,  exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Validate INPUT_SOURCE_PATH
if not os.path.exists(INPUT_SOURCE_PATH):
    print(f'❌ Source not found: {INPUT_SOURCE_PATH}')
    print('   Check the path and make sure Drive is mounted.')
elif not os.path.isdir(INPUT_SOURCE_PATH):
    print(f'❌ Expected a folder but found a file: {INPUT_SOURCE_PATH}')
    print('   Please update INPUT_SOURCE_PATH to point to a directory.')
else:
    # Process as a directory
    input_folder_name = os.path.basename(INPUT_SOURCE_PATH)
    input_folder_parent_dir = os.path.dirname(INPUT_SOURCE_PATH)

    # Output ZIP will be named after the input folder and placed in the same directory
    output_zip_file_name = f'{input_folder_name}_compressed.zip'
    OUTPUT_ZIP_PATH = os.path.join(input_folder_parent_dir, output_zip_file_name)
    zip_filename = output_zip_file_name # For use in CELL 4

    # Derive SERIAL_PREFIX from the input folder name
    # If the folder name contains ' - ', use the part after it. Otherwise, use the whole name.
    if ' - ' in input_folder_name:
        SERIAL_PREFIX = input_folder_name.split(' - ', 1)[1].strip()
    else:
        SERIAL_PREFIX = input_folder_name.strip()

    # Collect videos directly from the folder
    SUPPORTED = ('.mp4', '.mov', '.avi', '.mkv', '.webm', '.m4v', '.flv')
    for root, _, files in os.walk(INPUT_SOURCE_PATH):
        for file in files:
            if os.path.splitext(file)[1].lower() in SUPPORTED:
                # Copy video to INPUT_DIR for processing
                src_path = os.path.join(root, file)
                dest_path = os.path.join(INPUT_DIR, file)
                with open(src_path, 'rb') as src_f, open(dest_path, 'wb') as dest_f:
                    dest_f.write(src_f.read())
                extracted.append(dest_path)

    print(f'✅ Folder found  : {input_folder_name}')
    print(f'   Serial prefix : {SERIAL_PREFIX}')
    print(f'   Videos found  : {len(extracted)}')
    print(f'   Preset        : {PRESET} (fast!)')
    print(f'   Output → {output_zip_file_name} in same Drive folder')
    for v in sorted(extracted):
        print(f'     📹 {os.path.basename(v)}  ({os.path.getsize(v)/1024:.1f} KB)')

    if not extracted:
        print("No supported video files found in the specified folder.")

# ============================================================
# CELL 3: 🚀 Compress All Videos (Parallel)
# ============================================================
import subprocess, os
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

SUPPORTED = ('.mp4', '.mov', '.avi', '.mkv', '.webm', '.m4v', '.flv')

def compress_one(args):
    idx, vpath = args
    serial_name = f'{SERIAL_PREFIX}_{idx:02d}.{OUTPUT_EXT}'
    out_path    = os.path.join(OUTPUT_DIR, serial_name)

    # Build FFmpeg command
    # Corrected: Escaped the backslash for the ffmpeg 'scale' filter
    vf  = f'scale=min({MAX_WIDTH}\\,iw):-2' if MAX_WIDTH else 'scale=trunc(iw/2)*2:trunc(ih/2)*2'
    cmd = ['ffmpeg', '-y', '-i', vpath, '-vf', vf,
           '-c:v', CODEC, '-crf', str(CRF), '-preset', PRESET]
    if CODEC == 'libx265':
        cmd += ['-tag:v', 'hvc1']
    cmd += ['-c:a', 'aac', '-b:a', '64k'] if KEEP_AUDIO else ['-an']
    cmd += ['-movflags', '+faststart', out_path]

    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        return {'ok': False, 'input': os.path.basename(vpath), 'error': r.stderr[:200]}

    orig_kb = os.path.getsize(vpath)    / 1024
    comp_kb = os.path.getsize(out_path) / 1024
    return {
        'ok':            True,
        'idx':           idx,
        'input':         os.path.basename(vpath),
        'output':        out_path,
        'output_name':   serial_name,
        'original_kb':   round(orig_kb, 1),
        'compressed_kb': round(comp_kb, 1),
        'savings_pct':   round((1 - comp_kb / orig_kb) * 100, 1)
    }

# Collect + sort videos
video_files = sorted(
    [f for f in glob.glob(os.path.join(INPUT_DIR, '*'))
     if os.path.splitext(f)[1].lower() in SUPPORTED]
)

if not video_files:
    print('❌ No videos found.')
else:
    total   = len(video_files)
    # Use up to 4 parallel workers (Colab has 2 CPU cores, but IO overlap helps)
    workers = min(4, total)
    print(f'🚀 Compressing {total} video(s) with {workers} parallel workers...\n')

    results_map = {}
    tasks = list(enumerate(video_files, start=1))

    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {executor.submit(compress_one, t): t for t in tasks}
        for fut in tqdm(as_completed(futures), total=total, desc='Compressing'):
            res = fut.result()
            if res['ok']:
                results_map[res['idx']] = res
            else:
                print(f'❌ {res["input"]}: {res["error"]}')

    # Sort results by index for ordered display
    results = [results_map[i] for i in sorted(results_map.keys())]

    print(f'\n{"New Name":<35} {"Original":>8} {"Compressed":>11} {"Saved":>7}')
    print('─' * 66)
    for r in results:
        print(f'{r["output_name"][:33]:<35} {r["original_kb"]:>6.1f}KB '
              f'{r["compressed_kb"]:>9.1f}KB {r["savings_pct"]:>6.1f}%')
    print('─' * 66)
    t_orig = sum(r['original_kb']   for r in results)
    t_comp = sum(r['compressed_kb'] for r in results)
    t_save = (1 - t_comp / t_orig) * 100
    print(f'{"TOTAL":<35} {t_orig:>6.1f}KB {t_comp:>9.1f}KB {t_save:>6.1f}%')
    print(f'\n✅ Done! {len(results)}/{total} compressed.')

# ============================================================
# CELL 4: 📦 Pack → Save directly to Google Drive
# ============================================================
# No download needed! ZIP appears in your Drive folder instantly.

import zipfile
import os

# 👇 CHANGE THIS — The new Google Drive folder where you want to upload the compressed videos
UPLOAD_TARGET_FOLDER = '/content/drive/MyDrive/FYDP Master Folder/FYDP Videos New Upload'

# Ensure the upload target folder exists
os.makedirs(UPLOAD_TARGET_FOLDER, exist_ok=True)

# Construct the final output path for the ZIP file
# zip_filename is already defined from Cell 2 (e.g., 'SB01 - পতাকা [Potaka]_compressed.zip')
FINAL_OUTPUT_ZIP_PATH = os.path.join(UPLOAD_TARGET_FOLDER, zip_filename)

if extracted: # Check if 'extracted' list contains any videos to compress
    print(f'📦 Writing ZIP to Drive at: {FINAL_OUTPUT_ZIP_PATH}')
    with zipfile.ZipFile(FINAL_OUTPUT_ZIP_PATH, 'w', zipfile.ZIP_DEFLATED) as zf:
        for r in results:
            zf.write(r['output'], r['output_name'])
            print(f'  ✔ {r["output_name"]}  ({r["compressed_kb"]} KB)')

    zip_kb = os.path.getsize(FINAL_OUTPUT_ZIP_PATH) / 1024
    print(f'\n🎉 Done!')
    print(f'   ZIP saved to : {FINAL_OUTPUT_ZIP_PATH}')
    print(f'   Total size   : {zip_kb:.1f} KB')
    print(f'   Videos       : {len(results)}')
    print(f'\n👉 Open Google Drive → navigate to "{UPLOAD_TARGET_FOLDER}" → find "{zip_filename}" → it is already updated!')
else:
    print('No videos were compressed, so no ZIP file was created.')

"""---
## 📋 Speed Comparison

| Preset | Speed | Quality impact |
|---|---|---|
| `veryslow` | 🐢 Slowest | Best compression ratio |
| `slow` | 🐌 Slow | Great |
| `medium` | 🚶 Normal | Good |
| `fast` | 🏃 Fast | Good |
| **`ultrafast`** | **⚡ 10x faster** | **Still excellent for 2–4s clips ✅** |


"""